# Generated by Django 4.0 on 2022-03-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='no-img', max_length=100),
        ),
    ]
