# Generated by Django 4.0 on 2022-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_product_description_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('HORROR', 'Horror'), ('ADVENTURE', 'Adventure'), ('COMEDY', 'Comedy'), ('KIDS', 'Kids')], max_length=20),
        ),
    ]
