# Generated by Django 4.0 on 2022-03-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_product_likes_alter_product_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_books', models.CharField(default='[]', max_length=500)),
                ('cart', models.CharField(default='[]', max_length=500)),
            ],
        ),
    ]
