# Generated by Django 4.0 on 2022-03-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[(1, 'ACTION'), (2, 'HORROR'), (3, 'ADVENTURE'), (4, 'COMEDY'), (5, 'KIDS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
