# Generated by Django 4.0 on 2022-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_product_genre_alter_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.IntegerField(choices=[(1, 'ACTION'), (2, 'HORROR'), (3, 'ADVENTURE'), (4, 'COMEDY'), (5, 'KIDS')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
